# -*- coding: utf-8 -*-
"""Echidna_Trainer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z3Zf05ti__uFtn2FG9PkEadHJQrqRYb4
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x
!pip install gpt_2_simple -t . --no-deps --upgrade
!pip install toposort
import gpt_2_simple as gpt2
from google.colab import drive

!cp /content/drive/MyDrive/Echidna/gpt_2_simple/gpt_2.py /content/gpt_2_simple/gpt_2.py

model_name = "355M"
gpt2.download_gpt2(model_name=model_name)

gpt2.mount_gdrive()
root_dir = '/content/drive/MyDrive/Echidna'

sess = gpt2.start_tf_sess()
gpt2.finetune(sess,
              root_dir + '/data/data.json',
              steps=4000,
              model_name=model_name,
              print_every=10,
              sample_every=200,
              save_every=500,
              run_name='echidna',
              restore_from='fresh'
              ) 
gpt2.copy_checkpoint_to_gdrive(run_name='echidna')





